AllCops:
  Exclude:
    - cerner-oauth1a.gemspec
    - Gemfile
    - Rakefile
AbcSize:
  Max: 18
ClassLength:
  Max: 200
EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  Max: 25
ParameterLists:
  Max: 10
