AllCops:
  Exclude:
    - cerner-oauth1a.gemspec
    - Gemfile
    - Rakefile
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Metrics/AbcSize:
  Max: 18
  Exclude:
    - lib/cerner/oauth1a/access_token.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/cerner/oauth1a/access_token.rb
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Exclude:
    - lib/cerner/oauth1a/access_token.rb
Style/GuardClause:
  Exclude:
    - lib/cerner/oauth1a/access_token.rb
