language: ruby
before_install: gem install bundler
script: bin/rspec
matrix:
  include:
    - name: "Ruby 2.5.x"
      rvm: ruby-2.5
    - name: "Ruby 2.6.x"
      rvm: ruby-2.6
    - name: "Ruby 2.6.x with JIT"
      rvm: ruby-2.6
      env: RUBYOPT="--jit"
    - name: "Ruby 2.7.x"
      rvm: ruby-2.7
    - name: "Ruby 2.7.x with JIT"
      rvm: ruby-2.7
      env: RUBYOPT="--jit"
    - name: "Ruby HEAD"
      rvm: ruby-head
    - name: "Ruby HEAD with JIT"
      rvm: ruby-head
      env: RUBYOPT="--jit"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
