language: ruby
rvm:
  - ruby-2.2.6
  - ruby-2.3.3
  - ruby-2.4.0
  - ruby-head
script: bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
