language: ruby
rvm:
  - ruby-2.4
  - ruby-2.5
  - ruby-2.6
  - ruby-head
before_install: gem install bundler
script: bin/rspec
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
